# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('sex', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
